### ISSUE TITLE
Errors when compiling in Chrome (Windows 10)

### ISSUE THREAD

**Issue by TricksterSam** [paolo-prete/Spontini#1]
In Chrome, when I make an adjustment and attempt to recompile, it either doesn't do anything or it throws this error:
**Error while connecting to JSVGCompileHelper.**
In the web console it added:
**Failed to load resource: net::ERR_EMPTY_RESPONSE**

I'm using Windows 10 and Lilypond 2,20.0.

**Comment by paolo-prete** [comment]
did you run the JSSVGCompiler and press "Start" button?

**Comment by paolo-prete** [comment]
Also, let me know if you set the "Path" variable as explained here https://lilypond.org/windows.html (both for Python and for Lilypond). Test if you can run Lilypond with that variable set.

**Comment by paolo-prete** [comment]
Not an issue?
