### ISSUE TITLE
Lilypond console

### ISSUE THREAD

**Issue by TricksterSam** [paolo-prete/Spontini#2]
Is there a way to see the Lilypond console to follow code errors when compiling?

**Comment by paolo-prete** [comment]
Yes, just open the browser javascript console

**Comment by paolo-prete** [comment]
You can check the Lilypond compiling output on the Javascript console of your browser (open "Web developer" ---> "Web console" on Firefox and "More tools" ---> "Developer tools" on Chrome/Chromium)

**Comment by paolo-prete** [comment]
Not an issue
