### ISSUE TITLE
Linux: Firefox error message; cannot open any file

### ISSUE THREAD

**Issue by papioara** [paolo-prete/Spontini#3]
Hello, 
thank you for this interesting tool - learned about it through the Lilypond mailing list on Nabble. I have tested it on my Linux machine (Linux Mint 19.3 Cinnamon), but did not get very far unfortunately. I tried several browsers: Vivaldi, Pale Moon, Opera and Firefox 77.
What works: 
I can start SpontiniHelper.py and choose a working directory
I can open the html file, and the page appears in my browser

What does not work:
I cannot open any file nor do I see one on a list.
In Firefox, which is maybe the most important browser on my list, there is an error message when I click on 'OPEN'' . I attach a screenshot - that's faster than a long description.
I hope you can find a solution or maybe understand right away what the error message means. Unfortunately I am not a programmer, so I do not understand what this message actually means.

Thank you for your help and thank you for your work, too.

![SpontiniErrorFirefox77](https://user-images.githubusercontent.com/31970041/85922209-ce521800-b881-11ea-8a16-b46dcee3eb85.png)

**Comment by paolo-prete** [comment]
Hello,

You have to do this, as explained in the documentation

*NOTE if you use Firefox browser*: visit "about:config" page and set
"dom.dialog_element.enabled" preference to "true".

Let me know if it's all ok, now.

Best

**Comment by papioara** [comment]
Hello,

Sorry for my stupidity! I just did not see this instruction! I enabled that setting, and now I can see files and choose them, too. I will continue testing and tell you what works and what does not, if I come across something.

Best 

Hajo

**Comment by paolo-prete** [comment]
No problem.

**Comment by papioara** [comment]
I just looked at the EasyCrossStaffExample1.ly file. I does not compile, because I have only LIlypond 2.19.44 on my machine as well as the latest stable one, and the Helper asks for 2.19.83 or 84. Can I set somewhere which Lilypond version should be used? Like in the configuration file?

**Comment by paolo-prete** [comment]
You can try to change 

\version "2.19.84"

with your version

\version "2.19.44"

and see if it works.
But, as explained in the DOC, the program has been tested with Lilypond >= 2.19.84.
Then, in order to not have surprises, install a version >= 2.19.84.

**Comment by paolo-prete** [comment]
Note that if you really want to try your version you have to set

\version "2.19.44" in ALL the included files (easy-cross-staff.ly, jssvg.ly) etc.

I don't encourage you to do that. Installing a newer Lilypond version is very easy and it has many benefits for you.
