### ISSUE TITLE
Doesn't handle the absence of python3-tk gracefully

### ISSUE THREAD

**Issue by ksnortum** [paolo-prete/Spontini#4]
System: Ubuntu 20.04.

When I first launch the server from the command line, I get this:

    $ python3 SpontiniServer.py
    Traceback (most recent call last):
      File "SpontiniServer.py", line 32, in <module>
        from tkinter.messagebox import showerror
    ModuleNotFoundError: No module named 'tkinter'

Workaround: install python3-tk.

**Comment by paolo-prete** [comment]
This is already documented as mandatory:

"Debian based distros (Ubuntu, Mint etc.)

sudo apt install python3 python3-tk python3-pip python3-venv"
